In [26]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('dataset_Facebook.csv',sep=";")

In [5]:
df.head(10)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142

In [11]:
#create subset 1 
subset1 = df[["Type","Category","Post Month"]]
print(subset1.head(10))

     Type  Category  Post Month
0   Photo         2          12
1  Status         2          12
2   Photo         3          12
3   Photo         2          12
4   Photo         2          12
5  Status         2          12
6   Photo         3          12
7   Photo         3          12
8  Status         2          12
9   Photo         3          12

In [12]:
#create subset 2 
subset2 = df[["comment","Type","like"]]
print(subset2.head(10))

   comment    Type    like
0        4   Photo    79.0
1        5  Status   130.0
2        0   Photo    66.0
3       58   Photo  1572.0
4       19   Photo   325.0
5        1  Status   152.0
6        3   Photo   249.0
7        0   Photo   325.0
8        0  Status   161.0
9        3   Photo   113.0

In [13]:
#merge 2 subsets 
merged = pd.concat([subset1,subset2] , axis=1)
print(merged.head(10))

     Type  Category  Post Month  comment    Type    like
0   Photo         2          12        4   Photo    79.0
1  Status         2          12        5  Status   130.0
2   Photo         3          12        0   Photo    66.0
3   Photo         2          12       58   Photo  1572.0
4   Photo         2          12       19   Photo   325.0
5  Status         2          12        1  Status   152.0
6   Photo         3          12        3   Photo   249.0
7   Photo         3          12        0   Photo   325.0
8  Status         2          12        0  Status   161.0
9   Photo         3          12        3   Photo   113.0

In [22]:
#sort values
merged = merged.sort_values(by=["comment"],ascending=False)
print(merged.head(10))

       Type  Category  Post Month  comment    Type    like
244   Photo         2           7      372   Photo  5172.0
460   Photo         3           2      146   Photo  1546.0
168   Photo         1           9      144   Photo  1622.0
288   Photo         1           6      103   Photo   469.0
228   Photo         2           7       64   Photo   367.0
142  Status         2          10       60  Status   859.0
3     Photo         2          12       58   Photo  1572.0
480   Photo         2           1       56   Photo   360.0
379   Photo         3           4       51   Photo  1998.0
152   Photo         2          10       47   Photo   358.0

In [24]:
merged.transpose()

,244,460,168,288,228,142,3,480,379,152,...,136,125,424,205,23,12,8,444,44,499
Type,Photo,Photo,Photo,Photo,Photo,Status,Photo,Photo,Photo,Photo,...,Link,Photo,Photo,Photo,Photo,Photo,Status,Photo,Photo,Photo
Category,2,3,1,1,2,2,2,2,3,2,...,1,1,1,1,3,2,2,2,1,2
Post Month,7,2,9,6,7,10,12,1,4,10,...,10,10,3,8,12,12,12,3,12,1
comment,372,146,144,103,64,60,58,56,51,47,...,0,0,0,0,0,0,0,0,0,0
Type,Photo,Photo,Photo,Photo,Photo,Status,Photo,Photo,Photo,Photo,...,Link,Photo,Photo,Photo,Photo,Photo,Status,Photo,Photo,Photo
like,5172.0,1546.0,1622.0,469.0,367.0,859.0,1572.0,360.0,1998.0,358.0,...,32.0,7.0,32.0,39.0,72.0,90.0,161.0,48.0,47.0,91.0

In [25]:
print(df.shape)

(500, 19)

In [29]:
#reshape the data
arr = np.array(df[["Post Month","Post Weekday"]].head(6))
reshaped = arr.reshape(3,4)
print(reshaped)

[[12  4 12  3]
 [12  3 12  2]
 [12  2 12  1]]